# Site settings
name: BrendelGroup
email: 
author: VB

keywords: jekyll, jekyll theme, jekyll framework, stuffthings
description: Theme derived from Slim Pickins by Chrianthropic

# Only use this if you are serving your site via Github Pages
github:
# url: "https://brendelgroup.github.io/"

header: yes
header_sm: images/RAMOSE-banner-small.jpg
header_med: images/RAMOSE-banner-medium.jpg
header_large: images/RAMOSE-banner-large.jpg
header_xl: images/RAMOSE-banner-xlarge.jpg


# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, .last_optimized]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

gems:
  - jekyll-feed

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

permalink: blog/:year/:title

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image:                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: 
twitter_card: true
twitter_image:                        #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
