# Site settings
name:   BrendelGroup
email:  vbrendel@indiana.edu
author: VB

keywords:    genomics, workflows
description: Computational workflows for genomics

# Note: The site uses a theme derived from
#         https://github.com/chrisanthropic/slim-pickins-jekyll-theme
#       Thanks to the author!

# Only use this if you are serving your site via Github Pages
github:
  url: "https://brendelgroup.github.io/"

header:        yes
header_sm:     images/RAMOSE-banner-small.jpg
header_med:    images/RAMOSE-banner-medium.jpg
header_large:  images/RAMOSE-banner-large.jpg
header_xl:     images/RAMOSE-banner-xlarge.jpg


# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, .last_optimized]


# Build settings
markdown: kramdown
kramdown:
   input: GFM

destination: _site

gems:
  - jekyll-feed

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

permalink: blog/:year/:title

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto
